version: '3.3'

services:
  web:
    build: .
    command: nodemon /usr/src/app/app.js
    volumes:
      - ./src:/usr/src/app/
    ports:
      - 8080:8080
    environment:
      - MODE=dev
      - PORT=8080
      - c
    networks:
      - disney
    depends_on:
      - web-db

  web-db:
    image: mongo:latest
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - disney
networks:
  disney: